### ISSUE TITLE
LookAheadGainReduction.cpp

### ISSUE THREAD

**Issue by tommymetz** [DanielRudrich/SimpleCompressor#1]
Hey this is super awesome and I LOVED the lookahead limiter explanation! It's amazing how hard it is to find good stuff on this. I was always referencing [this](https://christianfloisand.wordpress.com/2014/07/16/dynamics-processing-compressorlimiter-part-3/) but like you said it's explanation of look-ahead is to delay the input. 

One super helpful thing I thought would be if there were some high-level comments in LookAheadGainReduction.cpp, especially the process() function. Just explaining the different loops and conditionals would help it be understandable. Do you think that is possible? Just having a hard time understanding what's going on. What are the step and breakWasUsed variables?

**Comment by DanielRudrich** [comment]
Will do! :)

**Comment by DanielRudrich** [comment]
https://github.com/DanielRudrich/SimpleCompressor/commit/8009e5384e0f6735d2b5f543fe1514ecf6cd4356 <- hope that helps :)
Let me know if there are still things left which could use some better explanation!
